const nodemailer = require("nodemailer");

const headers = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
  "Content-Type": "application/json",
};

exports.handler = async (event) => {
  // Handle CORS preflight
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 204, headers, body: "" };
  }

  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: "Method not allowed" }),
    };
  }

  try {
    const data = JSON.parse(event.body || "{}");
    const { summary, meta } = data;

    if (!summary) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: "Missing summary in request body" }),
      };
    }

    const patientName = meta?.patientName || "New";

    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;
    const emailTo = process.env.EMAIL_TO || emailUser;

    if (!emailUser || !emailPass) {
      return {
        statusCode: 500,
        headers,
        body: JSON.stringify({
          error:
            "Server misconfigured: Set EMAIL_USER and EMAIL_PASS in Netlify env",
        }),
      };
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: emailUser,
        pass: emailPass, // Gmail App Password (not regular password)
      },
    });

    // const mailOptions = {
    //   from: `"Rheuma Bot" <${emailUser}>`,
    //   to: emailTo,
    //   subject: "🩺 New Patient Intake Summary",
    //   html: `
    //     <h2>Rheumatology Intake Summary</h2>
    //     <pre style="font-family: monospace; white-space: pre-wrap;">${JSON.stringify(summary, null, 2)}</pre>
    //   `,
    // };

    const mailOptions = {
      from: `"OCTA Bot" <${emailUser}>`,
      to: emailTo,
      subject: `🩺 ${patientName || "New"} Patient Intake Summary`,
      html: `
  <div style="font-family: Arial, sans-serif; color: #333; max-width: 700px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px; background: #fff;">
    <h2 style="color:#1a73e8; margin-bottom: 20px;">Clinical Summary Report</h2>

    <div style="margin-bottom: 20px;">
      <h3 style="text-transform: uppercase; font-size: 12px; color: #555;">Potential Clinical Impression</h3>
      <p style="font-size: 16px; color:#0b5394; margin-top:5px;">${summary?.differentialDiagnosis ?? "N/A"}</p>
    </div>

    <div style="margin-bottom: 20px; padding: 10px; background: #f5f5f5; border-radius: 8px;">
      <h3 style="font-size: 13px; font-weight: bold; color:#333; margin-bottom: 10px;">Category Breakdown</h3>
      <ul style="font-size: 14px; line-height: 1.5; padding-left: 20px;">
        <li><strong>Joint Path:</strong> ${summary?.categorySummary?.jointPath ?? "N/A"}</li>
        <li><strong>Systemic:</strong> ${summary?.categorySummary?.systemic ?? "N/A"}</li>
        <li><strong>Gut:</strong> ${summary?.categorySummary?.gut ?? "N/A"}</li>
        <li><strong>Psychological:</strong> ${summary?.categorySummary?.psych ?? "N/A"}</li>
        <li><strong>Ayurvedic:</strong> ${summary?.categorySummary?.ayurvedic ?? "N/A"}</li>
      </ul>
    </div>

    ${
      summary?.redFlagsDetected?.length > 0
        ? `<div style="margin-bottom:20px; padding:10px; background:#ffe5e5; border:1px solid #f5c2c2; border-radius:8px;">
            <h3 style="font-size:13px; font-weight:bold; color:#d32f2f;">⚠ Red Flags Identified</h3>
            <ul style="font-size:14px; padding-left:20px; color:#c62828;">
              ${summary.redFlagsDetected.map((rf) => `<li>${rf}</li>`).join("")}
            </ul>
          </div>`
        : ""
    }

    <div>
      <h3 style="text-transform: uppercase; font-size: 12px; color: #555; margin-bottom: 10px;">Detailed Q&A Transcript</h3>
      <div style="max-height: 300px; overflow-y: auto; background: #f5f5f5; border: 1px solid #ddd; padding:10px; border-radius:6px; font-size:13px;">
        ${
          summary?.fullTranscript
            ?.map(
              (item) => `
          <div style="margin-bottom:10px; border-bottom:1px solid #ddd; padding-bottom:5px;">
            <p style="font-style:italic; color:#555; margin:0;">Q: ${item?.q ?? "N/A"}</p>
            <p style="margin:2px 0 0 0; color:#333;">A: ${item?.a ?? "N/A"}</p>
          </div>
        `,
            )
            .join("") ?? "<p>N/A</p>"
        }
      </div>
    </div>

    <p style="margin-top:20px; font-size:11px; color:#777;">This summary was automatically generated by Rheuma Bot.</p>
  </div>
  `,
    };

    await transporter.sendMail(mailOptions);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ success: true }),
    };
  } catch (error) {
    console.error("Email error:", error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        error: "Failed to send email",
        details: error.message,
      }),
    };
  }
};
